services:
  frontend:
    image: saidivakar/shopsmart-frontend:latest
    container_name: shopsmart-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - shopsmart-network

  backend:
    image: saidivakar/shopsmart-backend:latest
    container_name: shopsmart-backend
    ports:
      - "5100:5100"
    env_file:
      - ./backend.env
    networks:
      - shopsmart-network

networks:
  shopsmart-network:
    driver: bridge
